language: php

dist: xenial

os: linux

arch:
  - s390x

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1
  - 8.2

matrix:
  allow_failures:
    - php: 7.1
    - php: 7.2
    - php: 7.3

install:
  - composer install --prefer-source --no-interaction --dev

script: vendor/phpunit/phpunit/phpunit